### ISSUE TITLE
Autoload Lua console causes memory domain not found on 2.3.3

### ISSUE THREAD

**Issue by Isotarge** [TASVideos/BizHawk#1791]
Loving the speed improvements in 2.3.3 but ran into a small issue with Lua Console autoloading.

Enabling Lua Console autoload and then restarting BizHawk and running [ScriptHawk](https://github.com/Isotarge/ScriptHawk) after booting Banjo-Kazooie (E) causes ScriptHawk to fail to load and the following error to appear in the Lua Console output:

`Error: NullHawk does not implement memory domains
Unable to find domain: EEPROM, falling back to current
Error: NullHawk does not implement memory domains
NLua.Exceptions.LuaException: unprotected error in call to Lua API (0)
   at NLua.Lua.PanicCallback(IntPtr luaState)
   at lua_error(lua_State* )
   at NLua.ObjectTranslator.throwError(IntPtr luaState, Object e)
   at NLua.Lua.SetPendingException(Exception e)
   at NLua.LuaMethodWrapper.call(IntPtr luaState)
   at NLua.MetaFunctions.runFunctionDelegate(IntPtr luaState)
   at lua_resume(lua_State* , Int32 )
   at BizHawk.Client.EmuHawk.EmuLuaLibrary.ResumeScript(LuaFile lf)
   at BizHawk.Client.EmuHawk.LuaConsole.<>c__DisplayClass57_1.<ResumeScripts>b__1()
   at BizHawk.Client.Common.LuaSandbox.Sandbox(Action callback, Action exceptionCallback)`

Seems to me like the Lua context (for memory domains?) isn't switched from NullHawk to Mupen64plus when switching cores after autoloading the Lua Console window.

Works fine in 2.3.2 with autoload and also works in 2.3.3 if the Lua Console isn't autoloaded but opened for the first time after loading the N64 core.

Cheers, keep up the great work.

**Comment by YoshiRulz** [comment]
see also #1716?

**Comment by adelikat** [comment]
This is unlreated to #1760 

Also, fixed in release branch
